<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOiep8kr\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOiep8kr/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOiep8kr.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOiep8kr\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOiep8kr\appProdProjectContainer([
    'container.build_hash' => 'Oiep8kr',
    'container.build_id' => 'c54b1237',
    'container.build_time' => 1633873011,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOiep8kr');
