<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9deimyo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9deimyo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9deimyo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9deimyo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9deimyo\appDevDebugProjectContainer([
    'container.build_hash' => '9deimyo',
    'container.build_id' => 'bfda2cfc',
    'container.build_time' => 1637360775,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9deimyo');
