<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG3s06xc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG3s06xc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerG3s06xc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerG3s06xc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerG3s06xc\appProdProjectContainer([
    'container.build_hash' => 'G3s06xc',
    'container.build_id' => '62c814ae',
    'container.build_time' => 1634815360,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG3s06xc');
