<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZg79hdl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZg79hdl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZg79hdl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZg79hdl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZg79hdl\appDevDebugProjectContainer([
    'container.build_hash' => 'Zg79hdl',
    'container.build_id' => 'faa17fd5',
    'container.build_time' => 1637360795,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZg79hdl');
